name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install coveralls

    - name: Run tests
      run: python -m unittest discover -s tests -p 'test_*.py'

    - name: Upload coverage to Coveralls
      run: coveralls