name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install coveralls

    - name: Run tests
      run: |
        python -m unittest discover -s tests -p 'test_*.py'
        echo "Tests completed successfully."

    - name: Collect coverage data
      run: |
        coverage run -m unittest discover -s tests -p 'test_*.py'
        coverage combine
        echo "Coverage data collected."

    - name: Upload coverage to Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        python -m coveralls
        echo "Coverage data uploaded to Coveralls."
    
